services:
  - type: web
    name: khaddam-pdf
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    preDeployCommand: apt-get update && apt-get install -y libreoffice
    region: oregon
    plan: free

